RAM_READ_DELAY 0.01
RAM_WRITE_DELAY 0.01
BUS_CTRL_DELAY 2
BUS_DATA_DELAY 10
BUS_MAX_CONNECT 8
BUS_TABLE_SIZE 512
SSD_SIZE 1
PACKAGE_SIZE 2
DIE_SIZE 2
PLANE_SIZE 1024
PLANE_REG_READ_DELAY 0.01
PLANE_REG_WRITE_DELAY 0.01
BLOCK_SIZE 64
BLOCK_ERASES 100000
BLOCK_ERASE_DELAY 2000
PAGE_READ_DELAY 25
PAGE_WRITE_DELAY 300
PAGE_ENABLE_DATA 1
MAP_DIRECTORY_SIZE 100
FTL_IMPLEMENTATION 5
BAST_LOG_BLOCK_LIMIT 1024
FAST_LOG_BLOCK_LIMIT 1024
CACHE_DFTL_LIMIT 512
PARALLELISM_MODE 2
VIRTUAL_BLOCK_SIZE 1
VIRTUAL_PAGE_SIZE 1
RAID_NUMBER_OF_PHYSICAL_SSDS 2
